#!/bin/sh
badgers=12
mushrooms=2
count=0

while true; do
  echo $cclear
  for badgers in `seq 1 12`; do
    echo $cred
    echo "Badgers!"
    sleep 0.65
  done
  if [ $count -eq 6 ]; then
    echo $cyellow
    echo "Muuushrooom!"
    sleep 1.25
    echo "Muuushrooom!"
    sleep 1.25
    echo $cblue
    echo "  _________ _______      _____   ____  __.___________._."
    echo " /   _____/ \      \    /  _  \ |    |/ _|\_   _____/| |"
    echo " \_____  \  /   |   \  /  /_\  \|      <   |    __)_ | |"
    echo " /        \/    |    \/    |    \    |  \  |        \ \|"
    echo "/_______  /\____|__  /\____|__  /____|__ \/_______  / __"
    echo "        \/         \/         \/        \/        \/  \/"
    sleep 5
    count=0
  else
    for mushrooms in `seq 1 2`; do
      echo $cyellow
      echo "Muuushrooom"
      sleep 1.25
      count=`expr $count + 1`
    done
  fi
done






