#!/bin/sh


hundreths=0
seconds=0
minutes=0
hours=0
days=0

while true; do    
  clear
  echo $SOL_red
  echo day:
  echo $day
  echo hour:
  echo $hour
  echo $SOl_yellow
  echo minute:
  echo $minutes
  echo $SOl_blue
  echo second:
  echo $seconds
  echo $SOL_yellow
  echo hundreth:
  echo $hundreths
  sleep 0.01
  hundreths=`expr $hundreths + 1`
  if [ $hundreths -eq 100 ]
  then
    seconds=`expr $seconds + 1`
    hundreths=0
  fi
  if [ $seconds -eq 60 ]
  then
    minutes=`expr $minutes + 1`
    seconds=0
fi
 if [ $minutes -eq 60 ]
  then
    hours=`expr $hours + 1`
    minutes=0
fi
if [ $hours -eq 24 ]
then
days=`expr $days + 1`
hours=0
fi
done


















